name: Test

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 16
          - 17
          - 18

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ matrix.os }}-${{ github.ref_name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.os }}-${{ github.ref_name }}-${{ matrix.node-version }}
            node-modules-${{ matrix.os }}-master-${{ matrix.node-version }}
            node-modules-${{ matrix.os }}-${{ github.ref_name }}-
            node-modules-${{ matrix.os }}-master-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i --no-fund

      - name: Check code styles
        run: npm run lint

      - name: Build the project
        run: npm run build
